# Generated by Django 4.2.1 on 2023-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="size",
            name="product",
        ),
        migrations.AddField(
            model_name="size",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="products.product",
            ),
        ),
    ]
