# Generated by Django 4.2.1 on 2023-05-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options'),
        ('products', '0005_alter_category_options_product_season_and_more'),
    ]

    operations = [
    ]
