# Generated by Django 4.2.1 on 2023-05-24 13:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20230521_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='product/no_image.png', upload_to=products.models.Photo.upload_to, verbose_name='Image'),
        ),
    ]
