# Generated by Django 4.2.1 on 2023-05-24 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_photo_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="size",
            unique_together={("size", "color", "product")},
        ),
    ]
